### ISSUE TITLE
Any krang bots out there?

### ISSUE THREAD

**Issue by bitcoiners** [inertia186/krang#1]
Hi there inertia. Thanks for creating krang. Do you know of any bots that were created with krang yet?
Looking for custom voting bot written in ruby.

**Comment by inertia186** [comment]
I haven't really announced it yet.  I use it in various projects, but it's not quite where I want it yet.

**Comment by bitcoiners** [comment]
Ic. Have you heard of Glastnost?
https://github.com/cyberpunk-ventures/glasnost
 Glasnost is a GraphQL app server for Golos/Steem blockchains
Wondering how it compares with sbds and if it would be a good idea to integrate it with rails..

**Comment by inertia186** [comment]
Seems like glasnost has a focus on posts/commands/stats, whereas sbds ingests all object types.  So if you need a way of, for example, doing a lookup on who delegated to a particular account, sbds will come in handy.
